bookcollector/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import URLPattern, path
from . import views

# all site routes /URLS go below. Specifies endpoints
urlpatterns = [
    # ('route', controller, nickname)
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('books/', views.books_index, name='books'),
    path('books/<int:book_id>/', views.books_detail, name='detail'),
    # new route used to show a form and create a book
    path('books/create/', views.BookCreate.as_view(), name='books_create'),

    # int:pk I believe is for class based views. B/c we are using the Django rules for class based views.
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='books_update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='books_delete'),

    path('books/<int:book_id>/add_feedback/', views.add_feedback, name='add_feedback'),

    # <int:book_id> this means that in our controller/view function we will have access to book_id as an argument (since we are the ones writing the function differently than class based views). 
    # 'books/<int:book_id>/add_photos/', this is the end point
    # views.add_photo, the view function responsible to handing the endpoint
    # name='add_photo', name property that we can use when we want to access this via a form.
    path('books/<int:book_id>/add_photo/', views.add_photo, name='add_photo'),


    path('books/<int:book_id>/assoc_store/<int:store_id>/', views.assoc_store, name='assoc_store'),

    path('stores/', views.StoreList.as_view(), name='stores_index'),
    path('stores/<int:pk>/', views.StoreDetail.as_view(), name='stores_detail'),
    path('stores/create/', views.StoreCreate.as_view(), name='stores_create'),
    path('stores/<int:pk>/update/', views.StoreUpdate.as_view(), name='stores_update'),
    path('stores/<int:pk>/delete/', views.StoreDelete.as_view(), name='stores_delete'),

    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from statistics import mode
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

#select options for feeding types in Feeding Model
SCORES = (
    ('G', 'Great'),
    ('O', 'Okay'),
    ('T', 'Terrible'),
)

# Django built a parent class called models that has a bunch of functionality built in.

class Store(models.Model):
    name = models.CharField(max_length=50)
    # color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stores_detail', kwargs={'pk': self.id})

# Book Model
# Name, author, description, price

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    price = models.IntegerField()
    stores = models.ManyToManyField(Store)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        # return self.name
        return f"{self.name} - {self.author}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'book_id': self.id})

    def score_for_today(self):
        return self.feedback_set.filter(date=date.today()).count() >= len(SCORES)

class Feedback(models.Model):
    # This title 'Feedback Date' will be seen by the user in the forms.
    date = models.DateField('feedback date')
    score = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=SCORES,
        # set the default value for meal to be 'B'
        default=SCORES[0][0]
  )

    # This is where the relationship is defined (one to many in this case)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_score_display()} on {self.date}' 

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=300)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for book_id: {self.book_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Feedback

class FeedbackForm(ModelForm):
    class Meta: 
        model = Feedback
        fields = ['date', 'score']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Book, Store, Photo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# login required for class based views
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import FeedbackForm
# Aws stuff
# uuid gives us a globally unique string
import uuid 
import boto3

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'book-collector-gk'

# Faux Cat Data - Database simulation
# class Book:
#     def __init__(self, name, author, description, price):
#         self.name = name
#         self.author = author
#         self.description = description
#         self.price = price

#     # Book objects that are being instantiated from the Book class.
# books = [
#     Book('Rich Dad Poor Dad', 'Robert T. Kiyosaki', ' What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!', 7),
#     Book('Think and Grow Rich', 'Napoleon Hill', '"Think and Grow Rich" is a motivational personal development and self-help book written by Napoleon Hill and inspired by a suggestion from Scottish-American businessman Andrew Carnegie."', 15),
#     Book('The Alchemist', 'Paulo Coelho', 'A Fable About Following Your Dream', 14),
# ]




# Create your views here.

# This is equivalent to our controller /routes (in express js)

def home(request):
    # return HttpResponse('<h1>Hello Mundão 📚📚📚</h1>')
    return render(request, 'home.html')

def about(request):
    # If you want t osend back raw txt or an html string use HttpResponse
    # return HttpResponse('About Page')

    # If you want to send back a template file instead use "render"
    # Django will look into the folder called templates and return the specific file.
    return render(request, 'about.html')

@login_required
def books_index(request):
    # books = Book.objects.all()
    # use code below if you want to order by id
    books = Book.objects.order_by('id')
    return render(request, 'books/index.html', {'books': books})

@login_required
def books_detail(request, book_id):
    # Get the individual book
    book = Book.objects.get(id=book_id)
    stores_book_not_available = Store.objects.exclude(id__in = book.stores.all().values_list('id'))

    # print(stores_book_not_available)
    # ps. in order to get the print, you must refresh the page, and it will show up at the terminal when server is running.

    # Instantiate our feeding form
    feedback_form = FeedbackForm()
    # Render template, pass it the book
    return render(request, 'books/detail.html', {'book': book, 'feedback_form': feedback_form, 'stores': stores_book_not_available })


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['name', 'author', 'description', 'price']
    success_url = '/books/'

    def form_valid(self, form):
      form.instance.user = self.request.user
      return super().form_valid(form)

class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['name', 'author', 'description', 'price']

class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = '/books/'


@login_required
def add_feedback(request, book_id):
	# create the ModelForm using the data in request.POST
  form = FeedbackForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feedback = form.save(commit=False)
    new_feedback.book_id = book_id
    new_feedback.save()
  return redirect('detail', book_id=book_id)

@login_required
def add_photo(request, book_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, book_id=book_id)
            photo.save()
        except:
            print('An error occurred - S3')
    return redirect('detail', book_id=book_id)

@login_required
def assoc_store(request, book_id, store_id):
    Book.objects.get(id=book_id).stores.add(store_id)
    return redirect('detail', book_id=book_id)

@login_required
def unassoc_store(request, book_id, store_id):
    Book.objects.get(id=book_id).stores.remove(store_id)
    return redirect('detail', book_id=book_id)


class StoreList(LoginRequiredMixin, ListView):
  model = Store

class StoreDetail(LoginRequiredMixin, DetailView):
  model = Store

class StoreCreate(LoginRequiredMixin, CreateView):
  model = Store
  fields = '__all__'
  success_url = '/stores/'

class StoreUpdate(LoginRequiredMixin, UpdateView):
  model = Store
  fields = ['name']

class StoreDelete(LoginRequiredMixin, DeleteView):
  model = Store
  success_url = '/stores/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/books/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Book Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ book.name }}</span>
        <p>Author: {{ book.author }}</p>
        <p>Description: {{ book.description }}</p>
        {% if book.price > 0 %}
          <p>Price: {{ book.price }}</p>
        {% else %}
          <p>Price: Free</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'books_update' book.id %}">Edit</a>
        <a href="{% url 'books_delete' book.id %}">Delete</a>
      </div>
    </div>

    <!-- Insert Photo Card here -->
    {% for photo in book.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}" alt="book image">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <!-- Photo button/form -->
    <form action="{% url 'add_photo' book.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
  </form>

  </div>

  <div class="col s6">
      <form action="{% url 'add_feedback' book.id %}" method="post">
        {% csrf_token %}
        {{ feedback_form.as_p }}
        <input type="submit" class="btn" value="Add feedback">
      </form>

      <!-- <br>
      {% if book.fed_for_today %}
        <div class="card-panel teal-text center-align">{{book.name}} has been fed all meals for today</div>
      {% else %}
        <div class="card-panel red-text center-align">{{book.name}} might be hungry</div>
      {% endif %} -->

    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Score</th></tr>
      </thead>
      <tbody>
        {% for feedback in book.feedback_set.all %}
          <tr>
            <td>{{feedback.date}}</td>
            <td>{{feedback.get_score_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row"> 
  <div class="col s6">
    <h5>Stores that carry "{{ book.name }}"</h5>
    {% if book.stores.count %}
      {% for store in book.stores.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ store.name }}</span>
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
        <h5>Book not available!</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h5>Stores that may not carry "{{ book.name }}"</h5>
    {% if stores.count %}
      {% for store in stores.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ store.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_store' book.id store.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{store.name}} Available in all the stores</h5>
    {% endif %}
  </div>

</div>


<!-- JS to create a date picker and init the meal dropdown -->
<script>
  // create a datepicker
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // initialize the meal select
  var selectEl = document.getElementById('id_score');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/books/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Book List</h1>

{% for book in books %}
  <div class="card">
    <!-- <a href="{{ book.id }}"> -->
    <a href="{% url 'detail' book.id %}">
    <div class="card-content">
      <span class="card-title">{{ book.name }}</span>
      <p>Author: {{ book.author }}</p>
      <p>Description: {{ book.description }}</p>
      {% if book.price > 0 %}
        <p>Price: {{ book.price }}</p>
      {% else %}
        <p>Price: Free</p>
      {% endif %}
    </div>
    </a>    
  </div>
{% endfor %}

{% endblock %}